apiVersion: openshift.redhat.com/v1alpha1
kind: Workshop
metadata:
  name: cloud-native-workshop
spec:
  user: 
    number: 10
    password: openshift
  source:
    gitURL: https://github.com/mcouliba/cloud-native-workshop
    gitBranch: "3.2"
  infrastructure:
    argocd:
      enabled: false
      operatorHub:
        channel: alpha
        clusterServiceVersion: argocd-operator.v0.0.4
    bookbag:
      enabled: false
      image:
        name: quay.io/mcouliba/cloud-native-workshop-bookbag
        tag: "3.1"
    codeReadyWorkspace:
      enabled: true
      operatorHub:
        channel: latest
        clusterServiceVersion: crwoperator.v2.1.1
      openshiftOAuth: false
    etherpad:
      enabled: flase
    gogs:
      enabled: true
      image:
        name: quay.io/gpte-devops-automation/gogs-operator
        tag: v0.12
    nexus:
      enabled: true
    pipeline:
      enabled: flase
      operatorHub:
        channel: dev-preview
        clusterServiceVersion: openshift-pipelines-operator.v0.10.7
    project:
      enabled: true
      devName: dev-project
      stagingName: staging-project
    serviceMesh:
      enabled: false
      operatorHub:
        channel: "1.0"
        clusterServiceVersion: servicemeshoperator.v1.0.10
    istioWorkspace:
      enabled: false
      image:
        name: quay.io/maistra/istio-workspace
        tag: v0.0.3
    vault:
      enabled: false
      image:
        name: vault
        tag: "1.3.3"
      agentInjectorImage:
        name: "hashicorp/vault-k8s"
        tag: "0.3.0"
    workshopper:
      enabled: flase
