apiVersion: openshift.redhat.com/v1alpha1
kind: Workshop
metadata:
  name: cloud-native-workshop
spec:
  user: 
    number: 10
    password: openshift
  source:
    gitURL: https://github.com/mcouliba/cloud-native-workshop
    gitBranch: "3.0"
  infrastructure:
    argocd:
      enabled: true
    codeReadyWorkspace:
      enabled: true
      operatorHub:
        channel: latest
        clusterServiceVersion: crwoperator.v2.0.0
    etherpad:
      enabled: true
    gogs:
      enabled: true
      image:
        name: quay.io/gpte-devops-automation/gogs-operator
        tag: v0.12
    nexus:
      enabled: true
    pipeline:
      enabled: true
      operatorHub:
        channel: dev-preview
        clusterServiceVersion: openshift-pipelines-operator.v0.8.2
    project:
      enabled: true
      devName: my-project
      stagingName: cn-project
    serviceMesh:
      enabled: true
      elasticSearchOperatorHub:
        channel: preview
        clusterServiceVersion: elasticsearch-operator.4.1.15-201909041605
      jaegerOperatorHub:
        channel: stable
        clusterServiceVersion: jaeger-operator.v1.13.1
      kialiOperatorHub:
        channel: stable
        clusterServiceVersion: kiali-operator.v1.0.8
      serviceMeshOperatorHub:
        channel: "1.0"
        clusterServiceVersion: servicemeshoperator.v1.0.3
    squash:
      enabled: false
    workshopper:
      enabled: true